name: 'Container Action Template'
description: 'GOSS Action'
author: 'tomwillfixit'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
